// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace db_task.Models
{
    public partial class phone
    {
        public int id { get; set; }
        [StringLength(15)]
        public string type { get; set; }
        [StringLength(15)]
        public string number { get; set; }
        public int? personId { get; set; }

        [ForeignKey("personId")]
        [InverseProperty("phone")]
        public virtual person person { get; set; }
    }
}